stages:
  - build
  - test

before_script:
  - python --version
  - pip install --upgrade pip

build:
  stage: build
  image: python:3.11
  script:
    - echo "Building project..."

test:
  stage: test
  image: python:3.11
  script:
    - echo "Running tests..."
    - python -m unittest discover -s ci_demo/tests